# Generated by Django 2.1.2 on 2018-11-05 22:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20180806_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete='NOTHING', related_name='convites_recebidos', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete='NOTHING', related_name='convites_feitos', to='perfis.Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete='NOTHING', related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
    ]
